[0m12:48:41.157851 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10668fa00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077d1900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077d11b0>]}


============================== 12:48:41.161046 | 43b03bdb-cd72-422c-80ed-88c5a50737ee ==============================
[0m12:48:41.161046 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:48:41.161416 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zelalemtegene/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt init my_project', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:48:41.170996 [debug] [MainThread]: Starter project path: /Users/zelalemtegene/.pyenv/versions/3.10.0/lib/python3.10/site-packages/dbt/include/starter_project
[0m12:48:41.176157 [info ] [MainThread]: 
Your new dbt project "my_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:48:41.176428 [info ] [MainThread]: Setting up your profile.
[0m12:48:41.176832 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m12:48:41.178365 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 0.08408317, "process_in_blocks": "0", "process_kernel_time": 0.114676, "process_mem_max_rss": "94191616", "process_out_blocks": "0", "process_user_time": 0.725968}
[0m12:48:41.178816 [debug] [MainThread]: Command `dbt init` failed at 12:48:41.178748 after 0.08 seconds
[0m12:48:41.179075 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10668fa00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077d3970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1077d35b0>]}
[0m12:48:41.179310 [debug] [MainThread]: Flushing usage events
[0m12:48:42.214372 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:10:54.312503 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ce79a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c04c70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c04520>]}


============================== 13:10:54.316769 | 0bb7aa0d-1733-460b-95e8-da8b76a5fb78 ==============================
[0m13:10:54.316769 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:10:54.317334 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zelalemtegene/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:10:54.329842 [info ] [MainThread]: dbt version: 1.9.1
[0m13:10:54.330346 [info ] [MainThread]: python version: 3.10.0
[0m13:10:54.330701 [info ] [MainThread]: python path: /Users/zelalemtegene/.pyenv/versions/3.10.0/bin/python
[0m13:10:54.330998 [info ] [MainThread]: os info: macOS-15.2-arm64-arm-64bit
[0m13:10:54.331301 [info ] [MainThread]: Using profiles dir at /Users/zelalemtegene/.dbt
[0m13:10:54.331571 [info ] [MainThread]: Using profiles.yml file at /Users/zelalemtegene/.dbt/profiles.yml
[0m13:10:54.331839 [info ] [MainThread]: Using dbt_project.yml file at /Users/zelalemtegene/Documents/week-7/dbt_project.yml
[0m13:10:54.332107 [info ] [MainThread]: Configuration:
[0m13:10:54.332361 [info ] [MainThread]:   profiles.yml file [[31mERROR not found[0m]
[0m13:10:54.332621 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m13:10:54.332872 [info ] [MainThread]: Required dependencies:
[0m13:10:54.333183 [debug] [MainThread]: Executing "git --help"
[0m13:10:54.354870 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--no-lazy-fetch]\n           [--no-optional-locks] [--no-advice] [--bare] [--git-dir=<path>]\n           [--work-tree=<path>] [--namespace=<name>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m13:10:54.355706 [debug] [MainThread]: STDERR: "b''"
[0m13:10:54.356046 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m13:10:54.356384 [info ] [MainThread]: Connection test skipped since no profile was found
[0m13:10:54.356796 [info ] [MainThread]: [31m2 checks failed:[0m
[0m13:10:54.357078 [info ] [MainThread]: dbt looked for a profiles.yml file in /Users/zelalemtegene/.dbt/profiles.yml, but did
not find one. For more information on configuring your profile, consult the
documentation:

https://docs.getdbt.com/docs/configure-your-profile


[0m13:10:54.357385 [info ] [MainThread]: Project loading failed for the following reason:
 project path </Users/zelalemtegene/Documents/week-7/dbt_project.yml> not found

[0m13:10:54.378884 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.13865842, "process_in_blocks": "0", "process_kernel_time": 0.15765, "process_mem_max_rss": "92979200", "process_out_blocks": "0", "process_user_time": 1.099116}
[0m13:10:54.379615 [debug] [MainThread]: Command `dbt debug` failed at 13:10:54.379517 after 0.14 seconds
[0m13:10:54.380328 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ce79a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c04d30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108bfea40>]}
[0m13:10:54.380813 [debug] [MainThread]: Flushing usage events
[0m13:10:55.485444 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:48:26.051607 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ff79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118d1ed0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118d1780>]}


============================== 13:48:26.056012 | cd749286-61d9-45d1-ad1c-1b889d77f0cb ==============================
[0m13:48:26.056012 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:48:26.056579 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zelalemtegene/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:48:26.057152 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/zelalemtegene/Documents/week-7/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:48:26.058912 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.072923206, "process_in_blocks": "0", "process_kernel_time": 0.14497, "process_mem_max_rss": "92192768", "process_out_blocks": "0", "process_user_time": 1.076433}
[0m13:48:26.059544 [debug] [MainThread]: Command `dbt run` failed at 13:48:26.059449 after 0.07 seconds
[0m13:48:26.059918 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107ff79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118d0dc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1118d1ea0>]}
[0m13:48:26.060267 [debug] [MainThread]: Flushing usage events
[0m13:48:27.286169 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:49:11.298963 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fc79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107edded0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107edd780>]}


============================== 13:49:11.304091 | fa637c91-0841-43c1-81a5-6e3a16048d6b ==============================
[0m13:49:11.304091 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:49:11.304718 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zelalemtegene/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m13:49:11.305310 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/zelalemtegene/Documents/week-7/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:49:11.307225 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.07701538, "process_in_blocks": "0", "process_kernel_time": 0.138493, "process_mem_max_rss": "92438528", "process_out_blocks": "0", "process_user_time": 1.066852}
[0m13:49:11.307860 [debug] [MainThread]: Command `dbt run` failed at 13:49:11.307766 after 0.08 seconds
[0m13:49:11.308232 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106fc79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107edcdc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107eddea0>]}
[0m13:49:11.308584 [debug] [MainThread]: Flushing usage events
[0m13:49:12.266071 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:50:20.762789 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076f79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110d1900>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110d11b0>]}


============================== 13:50:20.767057 | f167b90f-af4c-4242-960c-c4c75a0841b7 ==============================
[0m13:50:20.767057 [info ] [MainThread]: Running with dbt=1.9.1
[0m13:50:20.767659 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/zelalemtegene/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'static_parser': 'True', 'invocation_command': 'dbt init my_project', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:50:20.779754 [info ] [MainThread]: A project called my_project already exists here.
[0m13:50:20.781741 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 0.08708825, "process_in_blocks": "0", "process_kernel_time": 0.141808, "process_mem_max_rss": "92946432", "process_out_blocks": "0", "process_user_time": 1.075415}
[0m13:50:20.782362 [debug] [MainThread]: Command `dbt init` succeeded at 13:50:20.782269 after 0.09 seconds
[0m13:50:20.782756 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1076f79d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110d19c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1110d2d70>]}
[0m13:50:20.783167 [debug] [MainThread]: Flushing usage events
[0m13:50:21.857692 [debug] [MainThread]: An error was encountered while trying to flush usage events
